# Generated by Django 5.0.1 on 2024-02-08 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('para_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('para_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='wordmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('para_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.paragraphs')),
            ],
        ),
    ]
