# Generated by Django 5.0.1 on 2024-02-08 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 18, 30, 3, 961557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 18, 30, 3, 961557, tzinfo=datetime.timezone.utc)),
        ),
    ]
